### ISSUE TITLE
how to compile Father

### ISSUE THREAD

**Issue by xroot000** [mav8557/Father#5]
How to compile Father for using on all x64 linux systems?

**Comment by mav8557** [comment]
I'm not sure what you mean by this. If you mean compiling once and dropping on any x64 box, then that probably isn't going to work since the rootkit is a dynamic library, the dynamic linker can be in different places on different machines. Your best bet is compiling it inside of a container/VM that matches the OS and version you're going to install it on.

**Comment by xroot000** [comment]
so, its impossible to compile Father static?

**Comment by mav8557** [comment]
> so, its impossible to compile Father static?

It's a dynamic library, so you can't compile it statically.
